# Generated by Django 3.2.19 on 2024-02-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_topplaces_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topplaces',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
